# Generated by Django 3.1.5 on 2021-02-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='contexts',
            new_name='contents',
        ),
    ]
