# Generated by Django 3.1.5 on 2021-02-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('board', '0002_auto_20210204_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='태그'),
        ),
    ]
