# Generated by Django 3.1.5 on 2021-02-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='tag',
            new_name='tags',
        ),
    ]
